<a href="https://colab.research.google.com/github/supreeth1311/AI-ML-Labsheet/blob/main/aiml_labsheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy and Pandas

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
#1D array
import numpy as np


In [ ]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.shape

(4,)

In [ ]:
a1.size

4

In [ ]:
#2D array
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(2, 4)

In [ ]:
a2.size

8

In [ ]:
a2.ndim

2

In [ ]:
#3D array
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.shape

(1, 3, 3)

In [ ]:
a3.size

9

In [ ]:
a3.ndim

3

zero array

In [ ]:
import numpy as np
z1=np.zeros(3)
(z1)

array([0., 0., 0.])

In [ ]:
#changing data type
z1=np.zeros(3,dtype=int)
(z1)


array([0, 0, 0])

In [ ]:
z1.shape

(3,)

In [ ]:
z1.size

3

In [ ]:
z1.ndim

1

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
#2D array
z2=np.zeros((3,4))
(z2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
(z2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.size

12

In [ ]:
z2.ndim

2

In [ ]:
#3D array
z3=np.zeros((2,3,4))
(z3)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3=np.zeros((2,3,4),dtype=int)
(z3)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
type(z3)

numpy.ndarray

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.size

24

In [ ]:
z3.ndim

3

ones array

In [ ]:
#1D ones array
import numpy as np
a1=np.ones(3)
(a1)

array([1., 1., 1.])

In [ ]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [ ]:
type(a1)


numpy.ndarray

In [ ]:
a1.shape

(3,)

In [ ]:
a1.size

3

In [ ]:
a1.ndim

1

In [ ]:
#2D ones array
a2=np.ones((2,3))
(a2)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a2=np.ones((2,3),dtype=int)
(a2)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.size


6

In [ ]:
a2.ndim

2

In [ ]:
# 3D ones array
a3=np.ones((4,2,3))
(a3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a3=np.ones((4,2,3),dtype=int)
(a3)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.shape

(4, 2, 3)

In [ ]:
a3.size

24

In [ ]:
a3.ndim

3

full array


In [ ]:
import numpy as np
#1d full array
f1=np.full(3,9)
(f1)

array([9, 9, 9])

In [ ]:
f1=np.full(3,9,dtype=float)
f1

array([9., 9., 9.])

In [ ]:
type(f1)

numpy.ndarray

In [ ]:
f1.shape

(3,)

In [ ]:
f1.size

3

In [ ]:
f1.ndim

1

In [ ]:
# 2d full array
f2=np.full((3,4),9)
(f2)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
f2=np.full((3,4),9,dtype=float)
(f2)

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [ ]:
type(f2)

numpy.ndarray

In [ ]:
f2.shape

(3, 4)

In [ ]:
f2.size

12

In [ ]:
f2.ndim

2

In [ ]:
# 3D array
f3=np.full((2,3,4),9)
(f3)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [ ]:
f3=np.full((2,3,4),9,dtype=float)
(f3)

array([[[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]],

       [[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]]])

In [ ]:
type(f3)

numpy.ndarray

In [ ]:
f3.shape

(2, 3, 4)

In [ ]:
f3.size

24

In [ ]:
f3.ndim

3

add array

In [ ]:
a=np.array([5,10,])
b=np.array([4,5,6])
c=np.add(a,b)
print(c)

[5 7 9]


In [ ]:
a=np.array([5,10,20])
b=np.array([2,2,2])
c=np.subtract(a,b)
print(c)

[ 3  8 18]


In [ ]:
a=np.array([5,10,20])
b=np.array([2,2,2])
c=np.multiply(a,b)
print(c)

[10 20 40]


In [ ]:
a=np.array([5,10,20])
b=np.array([2,2,2])
c=np.divide(a,b)
c

array([ 2.5,  5. , 10. ])

In [ ]:
a=np.array([5,10,20])
b=np.array([2,2,2])
c=np.mod(a,b)
c

array([1, 0, 0])

In [ ]:
a=np.array([5,10,20])
b=np.array([2,2,2])
c=np.power(a,b)
c

array([ 25, 100, 400])